import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from '@/components/ui/carousel';
import Image from 'next/image';

function Slider() {
  return (
    <div className='flex justify-center overflow-hidden relative z-[1]'>
      <Carousel className='relative max-w-3xl flex-1'>
        <CarouselContent className='rounded-lg'>
          {[2, 1, 3].map((i) => (
            <CarouselItem key={i} className='flex justify-center items-center rounded-lg'>
              <div className='relative h-[360px] aspect-[16/9] max-w-full overflow-hidden rounded-lg'>
                <Image
                  src={`/img${i}.webp`}
                  alt={`slide${i}`}
                  layout='fill'
                  objectFit='cover' // Giữ tỷ lệ ảnh
                  quality={95}
                  className='rounded-lg transition-transform duration-300 ease-in-out hover:scale-110'
                />
                {/* <span className='absolute inline-block rounded bg-foreground/60 left-2 bottom-2 text-background/80 text-sm'>
                  Picture was generated by DALL-E.
                </span> */}
              </div>
            </CarouselItem>
          ))}
        </CarouselContent>
        <CarouselPrevious />
        <CarouselNext />
      </Carousel>
    </div>
  );
}

export default Slider;
