import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/header';
import { Toaster } from '@/components/ui/toaster';
import UserIdentify from '@/routes/UserIdentify';
import { LoadingOverlay } from '@/components/layout/loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='vi'>
      <body className={inter.className}>
        <LoadingOverlay width={90} height={90} />
        <UserIdentify />
        <Toaster />
        <Header />
        {children}
      </body>
    </html>
  );
}
